version: "3.8"
services:
  neighbour_seeker:
    build:
      context: .
    depends_on:
      - geodb
    environment:
      - PG_DSN=postgres://geo:secret@geodb:5432/geodb
      - PG_POOL_SIZE=10
    ports:
      - target: 8080
        published: 8080
    # eventually it connects to the DB, probably better than wait script
    restart: on-failure

  geodb:
    image: kartoza/postgis
    volumes:
      - "db_data:/var/lib/postgresql/data/"
    environment:
      - POSTGRES_USER=geo
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DBNAME=geodb
    expose:
      - "5432"

volumes:
    db_data:
